### ISSUE TITLE
Fully on premises solution?

### ISSUE THREAD

**Issue by vijaykumark** [3scale/3scale-amp-openshift-templates#9]
From the installation guide at https://support.3scale.net/guides/infrastructure/onpremises20-installation
there is a need to attach 3scale subscriptions from RHSM.
Is there a way to run these openshift templates on Openshift Origin without any 3scale subscriptions?

**Comment by MarkCheshire** [comment]
Subscriptions are necessary. It is possible to request an eval via Red Hat sales
